version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: showzy-postgres
    environment:
      POSTGRES_DB: showzy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: avd
    ports:
      - "5432:5432"
    networks:
      - showzy-net
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: showzy-redis
    ports:
      - "6379:6379"
    networks:
      - showzy-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: showzy-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"   # For AMQP
      - "15672:15672" # For Management UI
    networks:
      - showzy-net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: showzy-app
    depends_on:
      - postgres
      - redis
      - rabbitmq
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/showzy
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: avd
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      JWT_SECRET: tPjdsGAQzLlwC4pX8o7t6f1OdA1BCHb6Bz3FtP+Sh8I
    networks:
      - showzy-net

networks:
  showzy-net:
    driver: bridge

volumes:
  postgres_data:
